version: "3.5"

services:
  grape-01:
    build:
      context: network
    command: ["./docker-entrypoint.sh", "grape --dp 20001 --aph 30001 --bn 'grape-02:20002,grape-03:20003'"]
    restart: always
    network_mode: host
    ports:
     - 20001:20001
     - 30001:30001

  grape-02:
    build:
      context: network
    command: ["./docker-entrypoint.sh", "grape --dp 20002 --aph 40001 --bn 'grape-01:20001,grape-03:20003'"]
    restart: always
    network_mode: host
    ports:
     - 20002:20002
     - 40001:40001

  grape-03:
    build:
      context: network
    command: ["./docker-entrypoint.sh", "grape --dp 20003 --aph 50001 --bn 'grape-01:20001,grape-02:20002'"]
    restart: always
    network_mode: host
    ports:
     - 20003:20003
     - 50001:50001

  server:
    build:
      context: server
      args:
        - NODE_ENV=development
    command: ["make", "dev_server"]
    restart: always
    network_mode: host
    volumes:
      - /opt/node_modules
      - ./server:/opt
    ports:
      - 9229:9229
    env_file:
      - ./envs/server.env
    depends_on:
      - grape-01
      - grape-02
      - grape-03

  client:
    build:
      context: client
      args:
        - NODE_ENV=development
    command: ["make", "dev_client"]
    restart: always
    network_mode: host
    volumes:
      - /opt/node_modules
      - ./client:/opt
    ports:
      - 9228:9229
    env_file:
      - ./envs/client.env
    # depends_on:
    #   - server
